name: thumbhash_example
description: Demonstrates how to use the thumbhash package.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  thumbhash: ^0.1.0
  image: ^3.1.3

dependency_overrides:
  thumbhash:
    path: ../../thumbhash

dev_dependencies:
  pedantic: ^1.10.0
