name: thumbhash_example
description: A simple command-line application.
version: 0.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  thumbhash:
  image:

dependency_overrides:
  thumbhash:
    path: ../../thumbhash

dev_dependencies:
  pedantic: ^1.10.0
