name: flutter_thumbhash_example
description: Demonstrates how to use the flutter_thumbhash package.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_thumbhash: ^0.1.0

dependency_overrides:
  thumbhash:
    path: ../../thumbhash
  flutter_thumbhash:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
