name: thumbhash
description: Dart implementation of ThumbHash algorithm — a very compact representation of an image placeholder.
version: 0.1.0+1
repository: https://github.com/PiN73/thumbhash/tree/master/packages/thumbhash
homepage: https://evanw.github.io/thumbhash/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0
