name: flutter_thumbhash
description: A new Flutter package project.
version: 0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  thumbhash:

dependency_overrides:
  thumbhash:
    path: ../thumbhash

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
