name: flutter_thumbhash
description: Flutter implementation of ThumbHash algorithm.
version: 0.1.0
repository: https://github.com/PiN73/thumbhash/tree/master/packages/flutter_thumbhash
homepage: https://evanw.github.io/thumbhash/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  thumbhash: ^0.1.0

dependency_overrides:
  thumbhash:
    path: ../thumbhash

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
